{% set name = "bgzip" %}
{% set version = "0.5.1" %}


package:
  name: py-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bgzip-{{ version }}.tar.gz
  sha256: 9f80cf018befe8f8f201fb571cf42f74e8d72f5bfdf897f4b451286d8abc955f

build:
  number: 1
  script:
    - export BUILD_WITH_CYTHON=1  # [not win]
    - set BUILD_WITH_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - cython
    - setuptools
    - pip
    - python
    - zlib
  run:
    - python

test:
  imports:
    - bgzip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DataBiosphere/bgzip 
  summary: Utilities working with blocked gzip streams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dpryan79
